Update __init__.py
YouTwitFace/ini-parser pull request #3
Opened 2023-03-16 10:34 UTC by rainyday-var

in case ini file has lines like this, incoming value will be as int and isdigit raises an error.

try it out

[some]
key = '10'
key1 = 10

2023-03-16 10:57 UTC, vrumger requested changes

2023-03-16 10:57 UTC, vrumger commented on ini/__init__.py
> +    if str(value).isdigit() or (value.startswith('-') and value[1:].isdigit()):
```suggestion
    if isinstance(value, int) or value.isdigit() or (value.startswith('-') and value[1:].isdigit()):
```

2023-03-16 12:08 UTC, merged

2023-03-16 12:09 UTC, vrumger commented
good catch - thanks!

2023-03-17 11:00 UTC, dziaineka commented
@vrumger would you be so kind to update pypi package https://pypi.org/project/ini-parser/?

2023-03-17 11:02 UTC, vrumger commented
@dziaineka yeah, I'm pretty busy this weekend. I'll update it Sunday morning :)

2023-03-19 11:31 UTC, vrumger commented
@dziaineka I've updated it on pypi :)